function runAasGeometryPresetExample()
%RUNAASGEOMETRYPRESETEXAMPLE Demonstrate AAS geometry presets.
%
%   Runs three small EIRP CDF-grid jobs to compare:
%       1. R23/ITU default       (r23_1x3_default, 8x16 with 3 elements/subarray)
%       2. Explicit R23 default  (verifies API equivalence to default)
%       3. CTIA 7 GHz 1x6        (4x16 with 6 elements/subarray)
%
%   The R23/ITU configuration remains the default model. It represents
%   the source-aligned Extended AAS baseline used for WRC-27 sharing
%   studies. The ctia_7ghz_1x6 preset represents the CTIA 7 GHz AAS
%   design/sensitivity case (4x16 subarray, 6 elements per subarray,
%   768 total elements across two polarizations, ~32.2 dBi antenna gain,
%   ~90.8 dBm total macrocell EIRP at 58.6 dBm conducted power).

    here = fileparts(mfilename('fullpath'));
    repoRoot = fileparts(here);
    addpath(fullfile(repoRoot, 'matlab'));

    smallOpts = struct( ...
        'numMc',       4, ...
        'azGridDeg',   -30:10:30, ...
        'elGridDeg',   -10:5:10, ...
        'binEdgesDbm', -80:5:130, ...
        'percentiles', [5 50 95], ...
        'seed',        1, ...
        'numBeams',    3, ...
        'deployment',  'macroUrban', ...
        'computePointingHeatmap', false);

    fprintf('--- R23/ITU default (no preset argument) ---\n');
    resultDefault = runR23AasEirpCdfGrid(smallOpts);
    printGeometrySummary(resultDefault);

    fprintf('\n--- Explicit r23_1x3_default ---\n');
    resultR23 = runR23AasEirpCdfGrid(smallOpts, ...
        'aasGeometryPreset', 'r23_1x3_default');
    printGeometrySummary(resultR23);

    fprintf('\n--- CTIA 7 GHz 1x6 ---\n');
    resultCtia = runR23AasEirpCdfGrid(smallOpts, ...
        'aasGeometryPreset', 'ctia_7ghz_1x6');
    printGeometrySummary(resultCtia);

    fprintf('\n--- Comparison ---\n');
    fprintf('  Default      sectorEirpDbm = %.2f  antennaGainDbi = %.3f\n', ...
        resultDefault.stats.sectorEirpDbm, ...
        resultDefault.metadata.aasGeometry.calculatedAntennaGainDbi);
    fprintf('  R23 explicit sectorEirpDbm = %.2f  antennaGainDbi = %.3f\n', ...
        resultR23.stats.sectorEirpDbm, ...
        resultR23.metadata.aasGeometry.calculatedAntennaGainDbi);
    fprintf('  CTIA 1x6     sectorEirpDbm = %.2f  antennaGainDbi = %.3f\n', ...
        resultCtia.stats.sectorEirpDbm, ...
        resultCtia.metadata.aasGeometry.calculatedAntennaGainDbi);

    sameDefault = isequal(resultDefault.stats.counts, resultR23.stats.counts);
    fprintf('  Default and explicit r23_1x3_default produce equal counts: %d\n', ...
        sameDefault);
end

function printGeometrySummary(result)
    g = result.metadata.aasGeometry;
    fprintf('  preset                                = %s\n', g.aasGeometryPreset);
    fprintf('  arrayRows x arrayCols                  = %d x %d\n', ...
        g.arrayRows, g.arrayCols);
    fprintf('  subarrayElementRows x subarrayElementCols = %d x %d\n', ...
        g.subarrayElementRows, g.subarrayElementCols);
    fprintf('  totalPhysicalElementsAcrossPolarizations = %d\n', ...
        g.totalPhysicalElementsAcrossPolarizations);
    fprintf('  calculatedSubarrayGainDb               = %.4f\n', ...
        g.calculatedSubarrayGainDb);
    fprintf('  calculatedArrayGainDb                  = %.4f\n', ...
        g.calculatedArrayGainDb);
    fprintf('  calculatedAntennaGainDbi               = %.4f\n', ...
        g.calculatedAntennaGainDbi);
    if isfield(g, 'sectorEirpDbm')
        fprintf('  sectorEirpDbm                          = %.2f\n', ...
            g.sectorEirpDbm);
    end
    if isfield(g, 'totalConductedPowerDbm')
        fprintf('  totalConductedPowerDbm                 = %.2f\n', ...
            g.totalConductedPowerDbm);
    end
end
